name: TritonBench PR Test
on:
  pull_request:
    paths:
      - .github/workflows/pr.yml
      - .github/workflows/_linux-test-*.yml
      - tritonbench/**
  push:
    branches:
      - main

jobs:
  h100-meta-triton-test:
    uses: ./.github/workflows/_linux-test-h100.yml
    with:
      conda_env: "meta-triton"
  h100-triton-main-test:
    uses: ./.github/workflows/_linux-test-h100.yml
    with:
      conda_env: "triton-main"
  mi350-triton-main-test:
    uses: ./.github/workflows/_linux-test-mi350.yml
    with:
      conda_env: "triton-main"



concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
